name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub using secrets
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # SSH into EC2 instance and pull the latest Docker image from DockerHub
    - name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.8
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      # Check the current directory
      echo "Current directory:"
      pwd

      # List contents of home and app directories for debugging
      echo "Contents of home directory:"
      ls -la ~
      
      echo "Contents of ~/app directory:"
      ls -la ~/app

      # Update the repository and pull the latest image from Docker Hub
      cd ~/app || { echo "Directory ~/app does not exist"; exit 1; }
      if [ -f docker-compose.yml ]; then
        echo "Found docker-compose.yml, proceeding with pull and up."
        docker-compose pull
        docker-compose up -d
      else
        echo "docker-compose.yml not found in ~/app"
        exit 1
      fi
